//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        Projekt.CompositeType GetDataUsingDataContract(Projekt.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Projekt.CompositeType> GetDataUsingDataContractAsync(Projekt.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ZmianaMiejscaZamieszkania", ReplyAction="http://tempuri.org/IService1/ZmianaMiejscaZamieszkaniaResponse")]
        void ZmianaMiejscaZamieszkania(string PESEL, string MiejsceZamieszkania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ZmianaMiejscaZamieszkania", ReplyAction="http://tempuri.org/IService1/ZmianaMiejscaZamieszkaniaResponse")]
        System.Threading.Tasks.Task ZmianaMiejscaZamieszkaniaAsync(string PESEL, string MiejsceZamieszkania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NowyKlient", ReplyAction="http://tempuri.org/IService1/NowyKlientResponse")]
        void NowyKlient(string NrPESEL, string Nazwisko, string Imie, string MiejsceZamieszkania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NowyKlient", ReplyAction="http://tempuri.org/IService1/NowyKlientResponse")]
        System.Threading.Tasks.Task NowyKlientAsync(string NrPESEL, string Nazwisko, string Imie, string MiejsceZamieszkania);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NowyPojazd", ReplyAction="http://tempuri.org/IService1/NowyPojazdResponse")]
        void NowyPojazd(string PeselWlasciciela, string NrRejestracji, string Marka, string Model, int Rocznik, string Przebieg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NowyPojazd", ReplyAction="http://tempuri.org/IService1/NowyPojazdResponse")]
        System.Threading.Tasks.Task NowyPojazdAsync(string PeselWlasciciela, string NrRejestracji, string Marka, string Model, int Rocznik, string Przebieg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Przeglad", ReplyAction="http://tempuri.org/IService1/PrzegladResponse")]
        void Przeglad(string NrRejestracji, string Przebieg, int Waznosc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Przeglad", ReplyAction="http://tempuri.org/IService1/PrzegladResponse")]
        System.Threading.Tasks.Task PrzegladAsync(string NrRejestracji, string Przebieg, int Waznosc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Informacje", ReplyAction="http://tempuri.org/IService1/InformacjeResponse")]
        string Informacje(string PESEL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Informacje", ReplyAction="http://tempuri.org/IService1/InformacjeResponse")]
        System.Threading.Tasks.Task<string> InformacjeAsync(string PESEL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Rejestracja", ReplyAction="http://tempuri.org/IService1/RejestracjaResponse")]
        string Rejestracja(string PESEL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Rejestracja", ReplyAction="http://tempuri.org/IService1/RejestracjaResponse")]
        System.Threading.Tasks.Task<string> RejestracjaAsync(string PESEL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Waznosc", ReplyAction="http://tempuri.org/IService1/WaznoscResponse")]
        System.Nullable<System.DateTime> Waznosc(string PESEL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Waznosc", ReplyAction="http://tempuri.org/IService1/WaznoscResponse")]
        System.Threading.Tasks.Task<System.Nullable<System.DateTime>> WaznoscAsync(string PESEL);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp3.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp3.ServiceReference1.IService1>, WindowsFormsApp3.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Projekt.CompositeType GetDataUsingDataContract(Projekt.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Projekt.CompositeType> GetDataUsingDataContractAsync(Projekt.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public void ZmianaMiejscaZamieszkania(string PESEL, string MiejsceZamieszkania) {
            base.Channel.ZmianaMiejscaZamieszkania(PESEL, MiejsceZamieszkania);
        }
        
        public System.Threading.Tasks.Task ZmianaMiejscaZamieszkaniaAsync(string PESEL, string MiejsceZamieszkania) {
            return base.Channel.ZmianaMiejscaZamieszkaniaAsync(PESEL, MiejsceZamieszkania);
        }
        
        public void NowyKlient(string NrPESEL, string Nazwisko, string Imie, string MiejsceZamieszkania) {
            base.Channel.NowyKlient(NrPESEL, Nazwisko, Imie, MiejsceZamieszkania);
        }
        
        public System.Threading.Tasks.Task NowyKlientAsync(string NrPESEL, string Nazwisko, string Imie, string MiejsceZamieszkania) {
            return base.Channel.NowyKlientAsync(NrPESEL, Nazwisko, Imie, MiejsceZamieszkania);
        }
        
        public void NowyPojazd(string PeselWlasciciela, string NrRejestracji, string Marka, string Model, int Rocznik, string Przebieg) {
            base.Channel.NowyPojazd(PeselWlasciciela, NrRejestracji, Marka, Model, Rocznik, Przebieg);
        }
        
        public System.Threading.Tasks.Task NowyPojazdAsync(string PeselWlasciciela, string NrRejestracji, string Marka, string Model, int Rocznik, string Przebieg) {
            return base.Channel.NowyPojazdAsync(PeselWlasciciela, NrRejestracji, Marka, Model, Rocznik, Przebieg);
        }
        
        public void Przeglad(string NrRejestracji, string Przebieg, int Waznosc) {
            base.Channel.Przeglad(NrRejestracji, Przebieg, Waznosc);
        }
        
        public System.Threading.Tasks.Task PrzegladAsync(string NrRejestracji, string Przebieg, int Waznosc) {
            return base.Channel.PrzegladAsync(NrRejestracji, Przebieg, Waznosc);
        }
        
        public string Informacje(string PESEL) {
            return base.Channel.Informacje(PESEL);
        }
        
        public System.Threading.Tasks.Task<string> InformacjeAsync(string PESEL) {
            return base.Channel.InformacjeAsync(PESEL);
        }
        
        public string Rejestracja(string PESEL) {
            return base.Channel.Rejestracja(PESEL);
        }
        
        public System.Threading.Tasks.Task<string> RejestracjaAsync(string PESEL) {
            return base.Channel.RejestracjaAsync(PESEL);
        }
        
        public System.Nullable<System.DateTime> Waznosc(string PESEL) {
            return base.Channel.Waznosc(PESEL);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<System.DateTime>> WaznoscAsync(string PESEL) {
            return base.Channel.WaznoscAsync(PESEL);
        }
    }
}
